# Generated by Django 5.1.1 on 2024-09-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstagramAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("biography", models.TextField(blank=True)),
                ("followers_count", models.IntegerField()),
                ("follows_count", models.IntegerField()),
                ("posts_count", models.IntegerField()),
                ("profile_pic_url", models.URLField()),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PopularPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("caption", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("likes_count", models.IntegerField()),
                ("comments_count", models.IntegerField()),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popular_posts",
                        to="api.instagramanalysis",
                    ),
                ),
            ],
        ),
    ]
