# Generated by Django 5.1.1 on 2024-09-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instagramanalysis",
            old_name="followers_count",
            new_name="follower_count",
        ),
        migrations.RenameField(
            model_name="instagramanalysis",
            old_name="follows_count",
            new_name="following_count",
        ),
        migrations.AlterField(
            model_name="instagramanalysis",
            name="analyzed_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="instagramanalysis",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
